version: "3"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=nicole
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
  redis:
